In [2]:
print("Dataset size:", data.shape)
print("\nMissing values:\n", data.isnull().sum())
print("\nStrength category counts:\n", data['strength'].value_counts())

Dataset size: (669640, 2)

Missing values:
 password    1
strength    0
dtype: int64

Strength category counts:
 strength
1    496801
0     89702
2     83137
Name: count, dtype: int64

In [5]:
data = data.dropna()
weak_passwords = data[data['strength'] == 0]
medium_passwords = data[data['strength'] == 1]
strong_passwords = data[data['strength'] == 2]

weak_sampled = weak_passwords.sample(n=80000, random_state=42)
medium_sampled = medium_passwords.sample(n=80000, random_state=42)
strong_sampled = strong_passwords.sample(n=80000, random_state=42)

balanced_data = pd.concat([weak_sampled, medium_sampled, strong_sampled])
balanced_data = balanced_data.sample(frac=1, random_state=42).reset_index(drop=True)
print("New dataset size:", balanced_data.shape)
print("\nNew category counts:\n", balanced_data['strength'].value_counts())

New dataset size: (240000, 2)

New category counts:
 strength
2    80000
1    80000
0    80000
Name: count, dtype: int64

In [1]:
import pandas as pd
data = pd.read_csv("../data/processed/clean_passwords.csv")
data['password'] = data['password'].astype(str)
data['length'] = data['password'].apply(len)
data['lowercase_count'] = data['password'].apply(lambda x: sum(1 for c in x if c.islower()))
data['uppercase_count'] = data['password'].apply(lambda x: sum(1 for c in x if c.isupper()))
data['digit_count'] = data['password'].apply(lambda x: sum(1 for c in x if c.isdigit()))
data['special_count'] = data['length'] - (data['lowercase_count'] + data['uppercase_count'] + data['digit_count'])
data.head()

,password,strength,length,lowercase_count,uppercase_count,digit_count,special_count
0,Tom7uBDM5NQz2MFe,2,16,5,8,3,0
1,purralef5,1,9,8,0,1,0
2,dcBwFHTY0OQm1f2Y,2,16,5,8,3,0
3,e4gajg80,1,8,5,0,3,0
4,galdi27,0,7,5,0,2,0

In [2]:
import math
from collections import Counter

def calculate_entropy(password):
    if not password:
        return 0
    entropy = 0
    length = len(password)
    counts = Counter(password)
    for count in counts.values():
        probability = count / length
        entropy -= probability * math.log2(probability)
        return entropy

data['entropy'] = data['password'].apply(calculate_entropy)
data.to_csv("../data/processed/engineered_passwords.csv", index=False)
data.head()

,password,strength,length,lowercase_count,uppercase_count,digit_count,special_count,entropy
0,Tom7uBDM5NQz2MFe,2,16,5,8,3,0,0.250000
1,purralef5,1,9,8,0,1,0,0.352214
2,dcBwFHTY0OQm1f2Y,2,16,5,8,3,0,0.250000
3,e4gajg80,1,8,5,0,3,0,0.375000
4,galdi27,0,7,5,0,2,0,0.401051

In [1]:
import pandas as pd
data = pd.read_csv("../data/raw/raw_passwords.csv", on_bad_lines="skip")
data.head(10)

           password  strength
0          kzde5577         1
1          kino3434         1
2         visi7k1yr         1
3          megzy123         1
4       lamborghin1         1
5  AVYq1lDE4MgAZfNt         2
6          u6c8vhow         1
7          v1118714         1
8      universe2908         1
9          as326159         1